version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "80:8000"
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=ecoandrich
      - POSTGRES_PASSWORD=qangqang1234
      - POSTGRES_DB=ecoandrich
